name: Deploy

on:
  push:
    branches: ["main"]
  workflow_call:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v16
        with:
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: "website"

      - name: Extract artifact
        run: |
          set -eo pipefail
          tar -xzf website.tar.gz

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
